### ISSUE TITLE
unable to uninstall using the given instructions, possibly due to something going wrong during the install?

### ISSUE THREAD

**Issue by connory94** [ryanrudolfoba/SteamOS-Waydroid-Installer#56]
Decided to uninstall after the script seemed to not work as intended.
- no shortcuts were added in gaming mode
- when using the .desktop files, the icon shows up for a second before disappearing
- tried to enter "waydroid session start" in the terminal, got errors telling me that the display/sockets weren't set? can't make much sense of it as I'm not an expert. searching for the message online gave unrelated/no solutions. gave up around this point.
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/138651184/a47c33bf-78f6-47b7-b58e-cb48f33d5749)

Attempted to uninstall and got the following error:

![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/138651184/e47d1860-50a0-48a0-bf61-2a87ec4fd2a5)

I did get this message that said something along the lines of "cannot run this as root user" near the end of the install process, maybe that has something to do with the issue?

I'm guessing that the best way out is uninstalling, but I'm open to trying to get this to work

**Comment by ryanrudolfoba** [comment]
If there were errors encountered during the install, the script will automatically perform a cleanup and waydroid will also be uninstalled automatically.

I would suggest clone the repo again to get the latest version. I just pushed an update a few mins ago. Please let me know how it goes on the new version.

**Comment by connory94** [comment]
Thank you for the response and sorry for the late reply. I tried this just now and nothing has changed. All of the same issues persist

**Comment by ryanrudolfoba** [comment]
Can you take a screenshot of the error please?

**Comment by connory94** [comment]
The error only appeared the first time I ran the script, and hasn't shown up since. If it means anything, the message appeared in a popup rather than in the terminal. Didn't think anything of it at the time, so I ignored it

here's the output I got after running the script just now, if it helps:

Cloning into '/root/AUR/waydroid/waydroid_script'...
remote: Enumerating objects: 717, done.
remote: Counting objects: 100% (327/327), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 717 (delta 259), reused 238 (delta 199), pack-reused 390
Receiving objects: 100% (717/717), 21.74 MiB | 7.49 MiB/s, done.
Resolving deltas: 100% (437/437), done.
Casualsnek repo has been successfully cloned!
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-04-10
pacman keyring has been initialized!
binder kernel module has been installed!
loading packages...
warning: wlroots-0.16.2-1 is up to date -- reinstalling
warning: dnsmasq-2.89-1 is up to date -- reinstalling
warning: lxc-1:5.0.2-1 is up to date -- reinstalling
warning: libglibutil-1.0.74-1 is up to date -- reinstalling
warning: libgbinder-1.1.35-1 is up to date -- reinstalling
warning: python-gbinder-1.1.2-1 is up to date -- reinstalling
warning: waydroid-1.4.2-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (7) dnsmasq-2.89-1  libgbinder-1.1.35-1
             libglibutil-1.0.74-1  lxc-1:5.0.2-1
             python-gbinder-1.1.2-1  waydroid-1.4.2-1
             wlroots-0.16.2-1

Total Installed Size:  31.91 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] 
(7/7) checking keys in keyring                     [##########] 100%
(7/7) checking package integrity                   [##########] 100%
(7/7) loading package files                        [##########] 100%
(7/7) checking for file conflicts                  [##########] 100%
(7/7) checking available disk space                [##########] 100%
:: Processing package changes...
(1/7) reinstalling wlroots                         [##########] 100%
(2/7) reinstalling dnsmasq                         [##########] 100%
(3/7) reinstalling lxc                             [##########] 100%
(4/7) reinstalling libglibutil                     [##########] 100%
(5/7) reinstalling libgbinder                      [##########] 100%
(6/7) reinstalling python-gbinder                  [##########] 100%
(7/7) reinstalling waydroid                        [##########] 100%
:: Running post-transaction hooks...
(1/7) Creating system user accounts...
(2/7) Reloading system manager configuration...
(3/7) Creating temporary files...
/usr/lib/tmpfiles.d/steamos.conf:6: Duplicate line for path "/root", ignoring.
/usr/lib/tmpfiles.d/steamos.conf:23: Duplicate line for path "/var/empty", ignoring.
/usr/lib/tmpfiles.d/tmp.conf:12: Duplicate line for path "/var/tmp", ignoring.
/usr/lib/tmpfiles.d/var.conf:19: Duplicate line for path "/var/cache", ignoring.
(4/7) Arming ConditionNeedsUpdate...
(5/7) Reloading system bus configuration...
(6/7) Updating icon theme caches...
(7/7) Updating the desktop file MIME type cache...
waydroid and cage has been installed!
ln: failed to create symbolic link '/root/Desktop/Waydroid-Toolbox': No such file or directory
This seems to be a reinstall. No further config needed.
Waydroid has been successfully installed!

**Comment by connory94** [comment]
oh crap didn't mean to do that. please ignore.

**Comment by ryanrudolfoba** [comment]
Ok please check in Desktop Mode - do you have icon called Waydroid Toolbox?

Check also in Game Mode if you have the shortcut Android Waydroid Cage and if you have it try to launch it.

**Comment by connory94** [comment]
No icons appeared on the desktop itself, so I just checked for the .desktop file & these 3 are the only waydroid-related things I can find.

![8CAD2546-AC8A-4FE6-80C2-70D0942D4782](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/138651184/fe266e3e-4ea1-48be-ac58-7405fe2facb3)

![DE87DFC3-5727-4181-AB95-1D42235A4C86](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/138651184/45c69cd2-c75a-4760-a265-79f79f7ef793)

**Comment by ryanrudolfoba** [comment]
This is a strange one. Try this please -

sudo rm -rf ~/waydroid (be careful on this command make sure no typos!)

after that run the script again.

**Comment by connory94** [comment]
no luck. nothing's changed, unfortunately.

**Comment by ryanrudolfoba** [comment]
sorry for late reply. I'm confused on the state of waydroid install in your machine. Try this please to check if installed or not -

ls /usr/bin/waydroid*

if nothing shows up in there it means waydroid is not installed.

**Comment by ryanrudolfoba** [comment]
havent heard back so closing this issue. please feel free to reopen if need further help.

**Comment by connory94** [comment]
oh my god I'm sorry for not responding earlier! had a bunch of work piled onto me and I completely forgot about this. tried this back when you first messaged and still got nothing. At this point, I've given up and don't feel like continuing. should I keep the issue closed or should I keep trying for future reference?
